### ISSUE TITLE
Enable selecting the seed being donated

### ISSUE THREAD

**Issue by rogargon** [UdL-EPS-SoftArch/seedbank-gei#24]
Right now it is just possible to define:
<img width="1368" alt="image" src="https://github.com/UdL-EPS-SoftArch/seedbank-gei/assets/1313870/f0c77b3a-8e8a-4e31-8ac5-dd4688c1c56f">

Make it possible to select from the registered seeds.

**Comment by Pablito2020** [comment]
@rogargon for now, we implemented on 9388e634aee944f39452c1e6abb64630e358b6b8  the selector element that shows the diferent type of seeds you can donate.

The problem we're having is that, in the backend entities,  a seed has a relation with multiple batches but, it only allows one batch to be related to it (For example, if you create a seed on the backend, and  two donations, it only allows you to do seed.setOf(donation1), but it doesn't allow you to relation this seed with multiple donations (seed.setOf(donation1, donation2, ....)).

The donation doesn't have any "seed" field either, which makes us think what should we do on this case? We tried:
1) Create a donation and then update the seed to have a relation with this donation (but this is useless, since, if we create a new donation, the relation will be broken, since a seed can only have one relation (as for today)).
2) Create a donation that has the seed field on it (isn't implemented on the backend).

Thanks in advance.

**Comment by rogargon** [comment]
You are right, the model implementation is wrong though the diagram is fine. The relation "of" should be in Batch and pointing to the Seed for that Batch, not in Seed as implemented right now. That is a bug that you can fix in the API
